### ISSUE TITLE
be able to pass a header to a specific request

### ISSUE THREAD

**Issue by theigor** [Maroo-us/brex-api#2]
Brex is about to start requiring an Idempotency-Key header for some requests
- https://developer.brex.com/docs/idempotency/
- https://developer.brex.com/openapi/payments_api/#operation/createTransfer!in=header&path=Idempotency-Key&t=request

I don't see a way to pass this through the wrapper. Any plans for this or should I go around?

a new interface like `RequestHeaders` so things like `CreateTransferRequest` could extend it

Thanks!

**Comment by alexesprit** [comment]
Hi!

I've added a way to specify idempotency key for these requests. I decided to not extend CreateTransferRequest interface, but add a new method argument, where you can specify the key:

```ts
    const res = await client.transfers.create(
      {
        amount: {
          amount: 799,
          currency: 'USD',
        },
        description: 'Test transfer',
        counterparty: {
          type: 'VENDOR',
          paymentInstrumentId: 'xxx',
        },
        externalMemo: 'ACH PMT',
        originatingAccount: {
          id: 'yyy',
          type: OriginatingAccountType.Cash,
        },
      },
      { idempotencyKey: '123-456' }
    )
```

I hope this will work for you.
